repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      # - id: check-added-large-files

  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.13.6
    hooks:
      - id: markdown-link-check
        args: [-q]

  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v1.0.0
    hooks:
      - id: sphinx-lint

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.5
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/numpy/numpydoc
    rev: v1.8.0
    hooks:
    - id: numpydoc-validation
      files: ^src/
      exclude: ^tests/|src/scribe_data/check/check_query_forms.py|src/scribe_data/cli/interactive.py|src/scribe_data/load/data_to_sqlite.py|src/scribe_data/wikidata/parse_dump.py|src/scribe_data/utils.py|src/scribe_data/cli/cli_utils.py|src/scribe_data/cli/download.py|src/scribe_data/cli/get.py|src/scribe_data/cli/list.py|src/scribe_data/cli/version.py|src/scribe_data/check/.*|src/scribe_data/check/check_missing_forms/.*|src/scribe_data/cli/.*|src/scribe_data/load/.*|src/scribe_data/wikidata/.*|src/scribe_data/wikidata/check_query/.*|src/scribe_data/unicode/.*|src/scribe_data/.*__init__\.py
